import { Session } from '../sheets/schema';
import { getRedis } from './redis';
import { sendPush } from './ntfy';
import { deliver } from './notifications';
import { currentWeekGameDayCandidates, getWeeklyMilestones, formatEasternMoment, formatGameDate } from './time';
import { DEFAULT_GAME_TIME } from './scheduling';

/**
 * Noticing that something the week needs has not been done.
 *
 * Nothing here runs on a schedule. GitHub Actions crons used to open and close
 * registration, and they routinely fired hours late or not at all, so
 * registration now follows each session's own window with nothing to run
 * (ADR-0009). What is left to forget is done by hand: generating teams and
 * sending the game-day email. And a week can have no game at all.
 *
 * So this runs on ordinary web traffic, off the same read the homepage already
 * makes, and asks a question the app can answer from state it already has:
 * *given the time, does this week look like those steps were taken?*
 *
 * That it needs a visitor is a real limitation and an acceptable one: the
 * steps it watches matter most in the hours when people are looking at the
 * game.
 */

/**
 * How long after a step was due before this reports it, so an organizer who is
 * a little late is not nagged on the minute.
 */
const GRACE_MS = 2 * 60 * 60 * 1000;

/** How long one alert suppresses the next for the same week and job. Long
 * enough that a busy Monday sends one push rather than a hundred, short enough
 * that an unfixed problem asks again the next morning. */
const REPEAT_AFTER_SECONDS = 12 * 60 * 60;

export interface MissedJob {
  /** What did not happen, so the alert names it. Two are steps the organizer
   * takes by hand, which is exactly why they need watching. `nothing-scheduled`
   * is the week having no games at all. */
  job: 'generate-teams' | 'game-day-email' | 'nothing-scheduled';
  /** Which session this is about, '' for `nothing-scheduled`. Part of the
   * alert-suppression key, so two sessions with the same problem do not
   * silence each other. */
  sessionId?: string;
  message: string;
  /** Whether a player is blocked right now, as opposed to the organizer
   * being short of information. */
  urgent: boolean;
}

/**
 * Which steps look like they were never taken, given the clock and the sheet.
 *
 * Pure, and free: no I/O, so the read path can ask on every cache miss and pay
 * nothing in the overwhelmingly common case where the answer is "none".
 *
 * Each check is written against the *observable consequence* of a step, in
 * the sheet, not against whether a button was pressed.
 */
export function missedJobsFor(session: Session, now: Date = new Date()): MissedJob[] {
  const missed: MissedJob[] = [];

  const milestones = getWeeklyMilestones(session.gameDate, session.gameTime, session);
  const overdue = (at: Date) => now.getTime() > at.getTime() + GRACE_MS;

  // A cancelled session is a decision, not a failure: nothing is owed to it.
  if (session.status === 'cancelled') return missed;

  // Teams are generated by a button. The lock has passed and there are none.
  // Not for a practice week, which has no sides to pick (see adminAgenda).
  if (session.format !== 'practice' && session.teamsStatus === '' && overdue(milestones.cutoffStart)) {
    missed.push({
      job: 'generate-teams',
      message: `No teams for ${formatGameDate(session.gameDate)}. The roster locked ${formatEasternMoment(milestones.cutoffStart)}.`,
      urgent: false,
    });
  }

  // The game-day email is a button, so the thing to watch is the organizer
  // forgetting it, not a workflow failing. Reported from two hours before the
  // first pitch — late enough that a normal week has already sent, early
  // enough that there is still time to act on the push.
  const NUDGE_BEFORE_GAME_MS = 2 * 60 * 60 * 1000;
  if (
    session.remindersSentAt === '' &&
    now.getTime() > milestones.gameStart.getTime() - NUDGE_BEFORE_GAME_MS &&
    now.getTime() < milestones.gameStart.getTime()
  ) {
    missed.push({
      job: 'game-day-email',
      message: `Nobody has been emailed about ${formatGameDate(session.gameDate)}. The game starts ${formatEasternMoment(milestones.gameStart)}.`,
      urgent: true,
    });
  }

  return missed;
}

/**
 * Every session's missed jobs, plus the one thing that is nobody's session:
 * the week having no games at all.
 *
 * Runs over the whole upcoming list rather than a single session, because a
 * week can hold several and each has its own lock, its own teams and its own
 * email to forget. A session far enough ahead reports nothing on its own —
 * every check inside `missedJobsFor` is gated on a milestone being overdue —
 * so no date filtering is needed here.
 *
 * **"Nothing is scheduled" replaced the cron creating a default Friday.** With
 * every session made by hand and no recurring schedule, a row the app invents
 * would appear on every player's homepage as a real game, which is worse than
 * the gap it papers over. So the organizer is told instead, and decides.
 */
export function missedJobsForWeek(sessions: Session[], now: Date = new Date()): MissedJob[] {
  const expectedGameDate = currentWeekGameDayCandidates(now)[0];
  const { registrationOpensAt } = getWeeklyMilestones(expectedGameDate, DEFAULT_GAME_TIME);

  if (sessions.length === 0) {
    if (now.getTime() <= registrationOpensAt.getTime() + GRACE_MS) return [];
    return [
      {
        job: 'nothing-scheduled',
        sessionId: '',
        message: `Nothing is scheduled. Registration for the week of ${formatGameDate(expectedGameDate)} should have opened ${formatEasternMoment(registrationOpensAt)}, and there is no game for anyone to sign up for.`,
        urgent: true,
      },
    ];
  }

  return sessions.flatMap((session) =>
    missedJobsFor(session, now).map((job) => ({ ...job, sessionId: session.sessionId }))
  );
}

/**
 * Whether this is the first report of `key` in the repeat window.
 *
 * Without Redis there is no shared memory, so it reports — once per instance
 * per cold start, which is noisier than intended but not silent. Silence is
 * the failure mode this whole module exists to remove, so that is the right
 * way to degrade.
 */
async function shouldReport(key: string): Promise<boolean> {
  const redis = getRedis();
  if (!redis) return !reportedThisProcess.has(key);

  const claimed = await redis.set(`watchdog:${key}`, '1', { nx: true, ex: REPEAT_AFTER_SECONDS });
  return claimed === 'OK';
}

const reportedThisProcess = new Set<string>();

// Read at a glance on a lock screen (voice.md rule 8), so each says what is
// missing rather than naming an internal job.
const PUSH_TITLES: Record<MissedJob['job'], string> = {
  'nothing-scheduled': 'Nothing scheduled',
  'generate-teams': 'No teams yet',
  'game-day-email': 'Game-day email not sent',
};

/**
 * Pushes one alert per missed job to the organizer's phone.
 *
 * Awaited but swallowed, like every other alert in this app: this runs off a
 * page load, and a watchdog that can fail a player's request is worse than the
 * problem it reports.
 */
export async function reportMissedJobs(sessions: Session[], now: Date = new Date()): Promise<void> {
  const missed = missedJobsForWeek(sessions, now);
  if (missed.length === 0) return;

  for (const { job, sessionId, message, urgent } of missed) {
    // Keyed per session, not per week: two sessions with the same problem are
    // two things the organizer has to fix, and a shared key would let the
    // first one silence the second for twelve hours.
    const key = `${sessionId || currentWeekGameDayCandidates(now)[0]}:${job}`;
    if (!(await shouldReport(key))) continue;
    reportedThisProcess.add(key);

    const sent = await deliver(`watchdog alert for ${key}`, () =>
      sendPush(PUSH_TITLES[job], message, {
        priority: urgent ? 5 : 4,
        tags: [urgent ? 'rotating_light' : 'warning'],
      })
    );
    // The claim is taken before sending so concurrent page loads don't all
    // push. If the push failed, give it back: otherwise one ntfy blip buys
    // twelve hours of silence about a week nobody can sign up for.
    if (!sent) await unclaim(key);
  }
}

async function unclaim(key: string): Promise<void> {
  reportedThisProcess.delete(key);
  try {
    await getRedis()?.del(`watchdog:${key}`);
  } catch (err) {
    console.error(`Could not release the watchdog claim for ${key}; it stays quiet until it expires.`, err);
  }
}

/** For tests, which need each case to start with nothing remembered. */
export function forgetWatchdogReports(): void {
  reportedThisProcess.clear();
}
